name: Publish Extension

on:
  push:
    tags:
      - "v*"
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install dependencies
        run: npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build extension
        run: npm run vsce:package

      - name: Publish to Open VSX
        run: npx ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}
